version: 0.2

phases:
  build:
    commands:
      - echo Entered the build phase...
      - cd StockPricesApp 
      - mvn clean package
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - StockPricesApp/target/StockPricesApp-0.0.1-SNAPSHOT.jar
  discard-paths: yes
